import { FORMATION, type FieldLook } from './gl/field'

export const FIELD_SECTION_IDS = [
  'hero',
  'leadership',
  'experience',
  'projects',
  'case-study',
  'approach',
  'vibe',
  'contact',
] as const

export type FieldSectionId = (typeof FIELD_SECTION_IDS)[number]

const FIELD_COLOR = {
  deepViolet: 0x35134f,
  plum: 0x571f75,
  violet: 0x7345d6,
  electricViolet: 0xa56bff,
  orchid: 0xcc7cff,
  magenta: 0xff3fce,
  rose: 0xff78c8,
  blush: 0xffe8fa,
  white: 0xfff7ff,
} as const

/**
 * Formation score, physical parameters, camera framing, and color
 * temperatures mapped onto the portfolio section IDs.
 */
export const FIELD_LOOKS: Record<FieldSectionId, FieldLook> = {
  hero: {
    formation: FORMATION.WORDMARK,
    spring: 42,
    damp: 0.86,
    turb: 0.55,
    turbScale: 0.22,
    swirl: 0,
    size: 1.05,
    opacity: 0.085,
    cam: [0, -3.6, 25],
    target: [0, -3.6, 0],
    fov: 42,
    fitWidth: 28,
    fitHeight: 11,
    bleed: false,
    anchor: 'top',
    cold: FIELD_COLOR.deepViolet,
    warm: FIELD_COLOR.electricViolet,
    hot: FIELD_COLOR.blush,
    exposure: 1.2,
    bloom: 0.5,
  },
  leadership: {
    formation: FORMATION.ORB,
    spring: 16,
    damp: 0.9,
    turb: 1.1,
    turbScale: 0.09,
    swirl: 0.055,
    size: 1,
    opacity: 0.05,
    cam: [0, 5.2, 23],
    target: [0, 0.4, 0],
    fov: 48,
    fitWidth: 14.5,
    fitHeight: 14.5,
    bleed: false,
    cold: FIELD_COLOR.plum,
    warm: FIELD_COLOR.magenta,
    hot: FIELD_COLOR.blush,
    exposure: 0.98,
    bloom: 0.55,
  },
  experience: {
    formation: FORMATION.STREAM,
    spring: 26,
    damp: 0.86,
    turb: 0.8,
    turbScale: 0.2,
    swirl: 0,
    size: 0.86,
    opacity: 0.046,
    cam: [0, -0.5, 22],
    target: [0, -0.5, 0],
    fov: 46,
    fitWidth: 31,
    fitHeight: 8,
    cold: FIELD_COLOR.deepViolet,
    warm: FIELD_COLOR.orchid,
    hot: FIELD_COLOR.blush,
    exposure: 0.96,
    bloom: 0.5,
  },
  projects: {
    formation: FORMATION.GLOBE,
    spring: 58,
    damp: 0.78,
    turb: 0.45,
    turbScale: 0.4,
    swirl: 0,
    size: 0.92,
    opacity: 0.078,
    cam: [5.8, 0, 20],
    target: [5.8, 0, 0],
    fov: 42,
    fitWidth: 16,
    fitHeight: 19,
    bleed: false,
    cold: FIELD_COLOR.violet,
    warm: FIELD_COLOR.rose,
    hot: FIELD_COLOR.white,
    exposure: 1.18,
    bloom: 0.7,
  },
  'case-study': {
    formation: FORMATION.BARS,
    spring: 64,
    damp: 0.76,
    turb: 0.4,
    turbScale: 0.42,
    swirl: 0,
    size: 0.9,
    opacity: 0.052,
    cam: [0, -0.6, 27],
    target: [0, -1.2, 0],
    fov: 44,
    fitWidth: 16.5,
    fitHeight: 11,
    bleed: false,
    cold: FIELD_COLOR.deepViolet,
    warm: FIELD_COLOR.electricViolet,
    hot: FIELD_COLOR.blush,
    exposure: 1.02,
    bloom: 0.6,
  },
  approach: {
    formation: FORMATION.GRAPH,
    spring: 50,
    damp: 0.8,
    turb: 0.4,
    turbScale: 0.45,
    swirl: 0.012,
    size: 0.88,
    opacity: 0.058,
    cam: [0, 0, 27],
    target: [0, 0, 0],
    fov: 45,
    fitWidth: 25,
    fitHeight: 14,
    cold: FIELD_COLOR.violet,
    warm: FIELD_COLOR.orchid,
    hot: FIELD_COLOR.blush,
    exposure: 1.06,
    bloom: 0.6,
  },
  vibe: {
    formation: FORMATION.LATTICE,
    spring: 40,
    damp: 0.84,
    turb: 0.55,
    turbScale: 0.3,
    swirl: 0.03,
    size: 0.82,
    opacity: 0.041,
    cam: [-3.5, -1, 30],
    target: [0, 0, 0],
    fov: 46,
    fitWidth: 29,
    fitHeight: 15.5,
    cold: FIELD_COLOR.plum,
    warm: FIELD_COLOR.rose,
    hot: FIELD_COLOR.blush,
    exposure: 0.94,
    bloom: 0.5,
  },
  contact: {
    formation: FORMATION.CORE,
    spring: 34,
    damp: 0.84,
    turb: 0.85,
    turbScale: 0.16,
    swirl: 0.09,
    size: 1.1,
    opacity: 0.072,
    cam: [0, 0, 24],
    target: [0, 0, 0],
    fov: 46,
    fitWidth: 27,
    fitHeight: 14,
    cold: FIELD_COLOR.deepViolet,
    warm: FIELD_COLOR.magenta,
    hot: FIELD_COLOR.white,
    exposure: 1.12,
    bloom: 0.9,
  },
}

export const BOOT_LOOK: FieldLook = {
  ...FIELD_LOOKS.hero,
  spring: 0.14,
  damp: 0.985,
  turb: 2.2,
  turbScale: 0.05,
  swirl: 0.02,
  opacity: 0,
  cam: [0, -3.6, 44],
  target: [0, -3.6, 0],
  fov: 54,
}
